const sozlukData = [
    { term: "API (Application Programming Interface)", definition: "Bir yazılımın başka bir yazılımla konuşmasını sağlayan arayüzdür. Veri alışverişi ve fonksiyon kullanımı için standartlar belirler.", category: "Backend" },
    { term: "Agile (Çevik)", definition: "Yazılım geliştirmede esnekliği, hızı ve müşteri geri bildirimini merkeze alan yinelemeli bir yönetim yaklaşımıdır.", category: "SDLC" },
    { term: "Algorithm (Algoritma)", definition: "Bir problemi çözmek veya bir işlemi gerçekleştirmek için adım adım izlenen mantıksal yol ve kurallar dizisidir.", category: "Temel" },
    { term: "Angular", definition: "Google tarafından geliştirilen, TypeScript tabanlı, büyük ölçekli tek sayfa uygulamaları (SPA) oluşturmak için kullanılan bir frameworktür.", category: "Frontend" },
    { term: "Array (Dizi)", definition: "Aynı türden verileri bellekte ardışık olarak saklayan ve indeks numarası ile erişilen temel bir veri yapısıdır.", category: "Veri Yapıları" },
    { term: "Backend", definition: "Bir web uygulamasının kullanıcı tarafından görülmeyen; sunucu, veritabanı ve API mantığının çalıştığı arka kısmıdır.", category: "Backend" },
    { term: "Binary (İkilik)", definition: "Sadece 0 ve 1 rakamlarından oluşan, bilgisayarların temel çalışma mantığını temsil eden sayı sistemidir.", category: "Temel" },
    { term: "Blockchain", definition: "Verilerin bloklar halinde, kriptografik olarak birbirine bağlı ve dağıtık bir ağ üzerinde tutulduğu kayıt sistemidir.", category: "Teknoloji" },
    { term: "Bug (Hata)", definition: "Yazılımın beklenen şekilde çalışmasını engelleyen mantıksal, sözdizimsel ya da sistemsel hatalardır.", category: "Test" },
    { term: "C#", definition: "Microsoft tarafından geliştirilen, nesne yönelimli, C tabanlı ve modern bir programlama dilidir.", category: "Dil" },
    { term: "Cache (Önbellek)", definition: "Veriye erişimi hızlandırmak amacıyla sık kullanılan bilgilerin geçici olarak saklandığı yüksek hızlı katmandır.", category: "Backend" },
    { term: "CI/CD", definition: "Sürekli Entegrasyon (Continuous Integration) ve Sürekli Dağıtım/Teslimat süreçlerini kapsayan otomasyon yaklaşımıdır.", category: "DevOps" },
    { term: "Cloud Computing (Bulut Bilişim)", definition: "İşlem gücü, veritabanı ve depolama gibi kaynakların internet üzerinden talep üzerine sunulmasıdır.", category: "DevOps" },
    { term: "Code Review (Kod İnceleme)", definition: "Yazılan kodun kalitesini artırmak için başka geliştiriciler tarafından incelenmesi ve geri bildirim verilmesi sürecidir.", category: "SDLC" },
    { term: "CSS (Cascading Style Sheets)", definition: "HTML öğelerinin web sayfasında nasıl görüneceğini (renk, düzen, tasarım) belirleyen stil dilidir.", category: "Frontend" },
    { term: "Database (Veritabanı)", definition: "Verilerin yapılandırılmış bir şekilde saklandığı, yönetildiği ve güncellendiği dijital sistemdir.", category: "Veri" },
    { term: "Docker", definition: "Yazılımların, tüm bağımlılıklarıyla birlikte 'konteyner' adı verilen izole birimlerde çalıştırılmasını sağlayan platformdur.", category: "DevOps" },
    { term: "DOM (Document Object Model)", definition: "HTML veya XML dökümanlarının nesne olarak temsil edildiği ve scriptler tarafından manipüle edilebildiği arayüzdür.", category: "Frontend" },
    { term: "Encapsulation (Kapsülleme)", definition: "Verilerin ve fonksiyonların bir sınıf içerisinde toplanarak dış erişimden gizlenmesi prensibidir (OOP).", category: "Dil" },
    { term: "Framework", definition: "Yazılım geliştirmeyi kolaylaştırmak ve standartlaştırmak için sunulan kapsamlı araç, kütüphane ve kurallar setidir.", category: "Temel" },
    { term: "Frontend", definition: "Web uygulamasının kullanıcının etkileşime girdiği; tasarım, animasyon ve arayüz mantığının bulunduğu kısmıdır.", category: "Frontend" },
    { term: "Full Stack", definition: "Hem istemci tarafı (frontend) hem de sunucu tarafı (backend) geliştirme konularında yetkin olan geliştiricidir.", category: "Kariyer" },
    { term: "Git", definition: "Kod değişikliklerini takip etmeye ve ekip olarak ortak çalışmaya olanak tanıyan dağıtık versiyon kontrol sistemidir.", category: "Araç" },
    { term: "GitHub", definition: "Git tabanlı projelerin saklandığı, paylaşıldığı ve iş birliği yapıldığı dünyanın en büyük bulut platformudur.", category: "Araç" },
    { term: "Haskell", definition: "Güçlü statik tiplemeye sahip, saf ve tamamen fonksiyonel bir programlama dilidir.", category: "Dil" },
    { term: "HTML (HyperText Markup Language)", definition: "Web sayfalarının yapısını ve içeriğini tanımlamak için kullanılan standart işaretleme dilidir.", category: "Frontend" },
    { term: "HTTP (Hypertext Transfer Protocol)", definition: "İstemci (browser) ile sunucu (server) arasındaki veri alışverişini düzenleyen temel protokoldür.", category: "Backend" },
    { term: "IDE (Integrated Development Environment)", definition: "Yazılım geliştirmek için editör, derleyici ve hata ayıklayıcı gibi araçları bir arada sunan arayüzdür.", category: "Araç" },
    { term: "Inheritance (Kalıtım)", definition: "Bir sınıfın özelliklerini ve metodlarını başka bir sınıfa aktarması prensibidir (OOP).", category: "Dil" },
    { term: "JavaScript", definition: "Web sayfalarına etkileşim ve dinamizm kazandıran, hem istemci hem de sunucu tarafında çalışabilen yaygın bir dildir.", category: "Dil" },
    { term: "JSON (JavaScript Object Notation)", definition: "Verileri anahtar-değer çiftleri şeklinde saklayan, insanlarca okunabilir, hafif bir veri değişim formatıdır.", category: "Veri" },
    { term: "Kubernetes", definition: "Konteynerize edilmiş uygulamaların dağıtımı, ölçeklendirilmesi ve yönetimini otomatize eden orkestrasyon sistemidir.", category: "DevOps" },
    { term: "Library (Kütüphane)", definition: "Belirli görevleri yerine getirmek için önceden yazılmış, yazılımcı tarafından çağrılan kod koleksiyonudur.", category: "Temel" },
    { term: "Linux", definition: "Açık kaynaklı, çok kullanıcılı ve özellikle sunucu tarafında yaygın tercih edilen işletim sistemi çekirdeğidir.", category: "OS" },
    { term: "Machine Learning (Makine Öğrenmesi)", definition: "Bilgisayarların verilerden öğrenmesini ve açıkça programlanmadan tahminler yapmasını sağlayan yapay zeka dalıdır.", category: "AI" },
    { term: "Microservices (Mikroservisler)", definition: "Büyük uygulamaların, birbirleriyle ağ üzerinden haberleşen küçük ve bağımsız servisler halinde tasarlandığı mimaridir.", category: "Mimar" },
    { term: "MongoDB", definition: "Verileri JSON benzeri dökümanlar halinde saklayan, ölçeklenebilir ve popüler bir NoSQL veritabanıdır.", category: "Veri" },
    { term: "MVC (Model-View-Controller)", definition: "Veri, arayüz ve kontrol mantığını birbirinden ayırarak kodun yönetilebilirliğini artıran tasarım desenidir.", category: "Mimar" },
    { term: "NoSQL", definition: "İlişkisel tablolar yerine döküman, grafik veya anahtar-değer çiftleri kullanan esnek veritabanı sistemleridir.", category: "Veri" },
    { term: "Object-Oriented Programming (OOP)", definition: "Yazılımı nesnelerin ve bunlar arasındaki ilişkilerin üzerine kurgulayan programlama yaklaşımıdır.", category: "Dil" },
    { term: "Open Source (Açık Kaynak)", definition: "Kaynak kodlarının herkes tarafından incelenebildiği, değiştirilebildiği ve paylaşılabildiği yazılım felsefesidir.", category: "Temel" },
    { term: "Padding", definition: "Bir elementin içeriği ile kenarlığı (border) arasında kalan iç boşluktur.", category: "Frontend" },
    { term: "Parsing", definition: "Verinin (kod, dize vb.) bileşenlerine ayrıştırılarak anlamlı bir yapıya dönüştürülmesi işlemidir.", category: "Temel" },
    { term: "Python", definition: "Okunabilirliği yüksek, çok yönlü, veri bilimi ve yapay zeka alanında oldukça popüler olan bir dildir.", category: "Dil" },
    { term: "Query (Sorgu)", definition: "Bir veritabanından veri çekmek veya veriyi güncellemek için gönderilen istektir (örn: SQL).", category: "Veri" },
    { term: "React", definition: "Meta tarafından geliştirilen, kullanıcı arayüzleri oluşturmak için kullanılan bileşen tabanlı bir JavaScript kütüphanesidir.", category: "Frontend" },
    { term: "Refactoring", definition: "Kodun dış davranışını bozmadan, iç yapısını ve okunabilirliğini iyileştirme işlemidir.", category: "SDLC" },
    { term: "Responsive Design", definition: "Web sitesinin farklı ekran boyutlarında (mobil, tablet, masaüstü) düzgün görünmesini sağlayan duyarlı tasarımdır.", category: "Frontend" },
    { term: "REST (Representational State Transfer)", definition: "HTTP üzerinden standart metotlarla (GET, POST, vb.) çalışan hafif bir web servis mimarisidir.", category: "Backend" },
    { term: "SaaS (Software as a Service)", definition: "Yazılımın bir abonelik modeliyle internet üzerinden hizmet olarak sunulmasıdır.", category: "Teknoloji" },
    { term: "Schema (Şema)", definition: "Veritabanındaki verilerin yapısını, ilişkilerini ve kısıtlamalarını tanımlayan taslak plandır.", category: "Veri" },
    { term: "Scrum", definition: "Agile metodolojisini uygulayan, 'Sprint' adı verilen kısa döngülerle ilerleyen proje yönetim çerçevesidir.", category: "SDLC" },
    { term: "SEO (Search Engine Optimization)", definition: "Web sitesinin arama motorlarında daha üst sıralarda yer alması için yapılan teknik ve içerik iyileştirmeleridir.", category: "Pazarlama" },
    { term: "SQL (Structured Query Language)", definition: "İlişkisel veritabanlarını yönetmek ve sorgulamak için kullanılan standart dildir.", category: "Veri" },
    { term: "Stack Overflow", definition: "Yazılımcıların soru sorduğu ve çözüm bulduğu dünyanın en büyük teknik topluluk platformudur.", category: "Topluluk" },
    { term: "Swift", definition: "Apple tarafından iOS ve macOS uygulama geliştirmek için tasarlanmış yüksek performanslı bir dildir.", category: "Dil" },
    { term: "Test Driven Development (TDD)", definition: "Yazılım geliştirmeye, koddan önce o kodun testlerini yazarak başlama yaklaşımıdır.", category: "Test" },
    { term: "TypeScript", definition: "JavaScript'e sıkı tipleme (Static Type) ekleyen ve Microsoft tarafından geliştirilen bir üst kümedir.", category: "Dil" },
    { term: "UI (User Interface)", definition: "Kullanıcının uygulama ile etkileşime girdiği görsel arayüzdür (butonlar, renkler, mizanpaj).", category: "Tasarım" },
    { term: "Unit Test", definition: "Bir yazılım projesindeki en küçük kod birimlerinin (fonksiyon, metod) tek başına test edilmesidir.", category: "Test" },
    { term: "UX (User Experience)", definition: "Kullanıcının uygulama ile etkileşimi sırasında yaşadığı deneyimin bütünsel kalitesidir.", category: "Tasarım" },
    { term: "Variable (Değişken)", definition: "Verileri saklamak ve üzerinde işlem yapmak için kullanılan, bellekteki isimlendirilmiş alanlardır.", category: "Temel" },
    { term: "Virtual Machine (VM)", definition: "Bir donanım üzerinde yazılımla taklit edilen, tamamen bağımsız ve izole bilgisayar sistemidir.", category: "DevOps" },
    { term: "Vue.js", definition: "Hafif, öğrenmesi kolay ve esnek bir yapıya sahip popüler bir JavaScript frameworküdür.", category: "Frontend" },
    { term: "Websocket", definition: "İstemci ve sunucu arasında çift yönlü ve gerçek zamanlı kesintisiz veri akışı sağlayan protokoldür.", category: "Backend" },
    { term: "XML (eXtensible Markup Language)", definition: "Verileri etiketler kullanarak saklayan ve taşıyan, genişletilebilir bir işaretleme dilidir.", category: "Veri" },
    { term: "Yield", definition: "Bir fonksiyondan değer döndürürken fonksiyonun durumunu koruyarak daha sonra devam etmesine olanak tanıyan ifadedir.", category: "Dil" },
    { term: "Z-Index", definition: "Web tasarımda öğelerin ekran üzerindeki derinliğini (ön-arka sırasını) belirleyen CSS özelliğidir.", category: "Frontend" },
    { term: "Abstraction (Soyutlama)", definition: "Karmaşık detayları gizleyerek sadece gerekli bilgileri kullanıcıya sunma işlemidir.", category: "OOP" },
    { term: "Asynchronous (Asenkron)", definition: "Bir işlemin tamamlanmasını beklemeden diğer işlemlere devam edebilme yeteneğidir.", category: "Temel" },
    { term: "Array List", definition: "Dinamik olarak büyüyebilen, dizileri temel alan bir veri yapısıdır.", category: "Veri Yapıları" },
    { term: "A/B Testing", definition: "Bir yazılımın iki farklı sürümünün kullanıcılar üzerinde performans karşılaştırmasıdır.", category: "Test" },
    { term: "API Gateway", definition: "Mikroservis mimarilerinde tüm istemci isteklerini karşılayan ve yönlendiren tek giriş noktasıdır.", category: "Mimar" },
    { term: "AWS (Amazon Web Services)", definition: "Dünyanın en kapsamlı ve yaygın kullanılan bulut platformudur.", category: "Cloud" },
    { term: "Azure", definition: "Microsoft'un kurumsal düzeydeki bulut bilişim hizmetidir.", category: "Cloud" },
    { term: "Bearer Token", definition: "İstek sahibinin kimliğini doğrulamak için HTTP başlığında kullanılan bir erişim belirtecidir.", category: "Güvenlik" },
    { term: "Bootstrap", definition: "Hızlı web geliştirmek için kullanılan en popüler açık kaynaklı CSS frameworküdür.", category: "Frontend" },
    { term: "Big O Notation", definition: "Bir algoritmanın çalışma süresinin veya alan gereksiniminin veri seti büyüdükçe nasıl değiştiğini açıklayan matematiksel ifadedir.", category: "Algoritma" },
    { term: "Brute Force", definition: "Bir problemi çözmek için tüm olası kombinasyonları deneme yöntemidir.", category: "Güvenlik" },
    { term: "Buffer Overflow", definition: "Bir programın kendisine ayrılan bellek alanından daha fazla veri yazarak yanındaki belleği bozması hatasıdır.", category: "Güvenlik" },
    { term: "Callback", definition: "Bir fonksiyonun argüman olarak başka bir fonksiyona geçirilmesi ve zamanı gelince çalıştırılmasıdır.", category: "JS" },
    { term: "C++", definition: "Sistem programlama ve performans odaklı uygulamalar için geliştirilmiş güçlü bir programlama dilidir.", category: "Dil" },
    { term: "Cookie (Çerez)", definition: "Web siteleri tarafından tarayıcıya kaydedilen küçük veri parçacıklarıdır.", category: "Web" },
    { term: "CORS (Cross-Origin Resource Sharing)", definition: "Tarayıcıların bir domainden başka bir domaine kaynak isteği yapmasını kısıtlayan ya da yöneten güvenlik mekanizmasıdır.", category: "Güvenlik" },
    { term: "CRUD", definition: "Create, Read, Update, Delete işlemlerinin baş harflerinden oluşan temel veritabanı işlemleridir.", category: "Veri" },
    { term: "Cryptography", definition: "Verilerin yetkisiz kişlerce okunmasını engellemek için şifrelenmesi bilimidir.", category: "Güvenlik" },
    { term: "Cyber Security", definition: "Dijital sistemleri, ağları ve verileri saldırılara karşı koruma disiplinidir.", category: "Güvenlik" },
    { term: "Data Mining (Veri Madenciliği)", definition: "Büyük veri yığınları içerisinden anlamlı modeller ve bilgiler çıkarma sürecidir.", category: "Veri" },
    { term: "Deadlock", definition: "İki veya daha fazla işlemin birbirinin elindeki kaynağı bekleyerek kilitlenmesi durumudur.", category: "İşletim Sistemleri" },
    { term: "Dependency Injection", definition: "Nesnelerin bağımlılıklarının dışarıdan enjekte edilmesi temeline dayanan tasarım desenidir.", category: "Tasarım" },
    { term: "DNS (Domain Name System)", definition: "İnternet alan adlarını IP adreslerine çeviren sistemdir.", category: "Ağ" },
    { term: "Django", definition: "Python ile hızlı ve güvenli web uygulamaları geliştirmek için tasarlanmış yüksek seviyeli bir frameworktür.", category: "Backend" },
    { term: "Elasticsearch", definition: "Büyük veri setleri üzerinde gerçek zamanlı arama ve analiz yapabilen dağıtık bir motor sistemidir.", category: "Veri" },
    { term: "Encryption (Şifreleme)", definition: "Veriyi sadece doğru anahtara sahip kişilerin okuyabileceği bir formata dönüştürme işlemidir.", category: "Güvenlik" },
    { term: "Express.js", definition: "Node.js için minimalist ve esnek bir web uygulama sunucusu frameworküdür.", category: "Backend" },
    { term: "Factory Pattern", definition: "Nesne oluşturma mantığını istemciden gizleyerek bir arayüz üzerinden nesne üretimini sağlayan desendir.", category: "Tasarım" },
    { term: "Firebase", definition: "Google'ın mobil ve web uygulamaları için sunduğu platformdur (Auth, DB, Hosting vb.).", category: "Cloud" },
    { term: "Firestore", definition: "Firebase'in ölçeklenebilir, bulut tabanlı NoSQL veritabanı servisidir.", category: "Veri" },
    { term: "Flutter", definition: "Google'ın tek bir kod tabanıyla mobil, web ve masaüstü uygulamalar geliştirmek için sunduğu SDK'dır.", category: "Mobil" },
    { term: "Garbage Collection", definition: "Kullanılmayan bellek alanlarının sistem tarafından otomatik olarak temizlenmesi işlemidir.", category: "Temel" },
    { term: "Gulp", definition: "Yinelenen görevleri (minification, derleme vb.) otomatize eden bir JavaScript tabanlı araçtır.", category: "Araç" },
    { term: "GraphQL", definition: "API'ler için geliştirilmiş, istemcinin sadece ihtiyaç duyduğu veriyi talep etmesine olanak tanıyan sorgu dilidir.", category: "Query" },
    { term: "GUI (Graphical User Interface)", definition: "Kullanıcının bilgisayarla görsel öğeler (ikonlar, pencereler) üzerinden etkileşime girdiği arayüzdür.", category: "Tasarım" },
    { term: "Hash Function", definition: "Veriyi sabit uzunlukta benzersiz bir diziye (hash) dönüştüren tek yönlü matematiksel fonksiyondur.", category: "Güvenlik" },
    { term: "Hosting", definition: "Web sitenizin dosyalarının internet üzerinden erişilebilir olması için bir sunucuda barındırılmasıdır.", category: "Web" },
    { term: "Identity Provider", definition: "Kullanıcı kimliklerini yöneten ve uygulamalara kimlik doğrulama hizmeti sunan sistemdir.", category: "Güvenlik" },
    { term: "Immutable", definition: "Oluşturulduktan sonra içeriği veya durumu değiştirilemeyen nesnelere denir.", category: "Temel" },
    { term: "Interface (Arayüz)", definition: "Bir sınıfın hangi metodlara sahip olması gerektiğini belirten ancak uygulama detayını içermeyen taslaktır.", category: "OOP" },
    { term: "IP Address", definition: "Ağ üzerindeki her cihaza atanan benzersiz tanımlayıcı numaradır.", category: "Ağ" },
    { term: "Iteration", definition: "Bir işlem dizisinin belirli bir hedef doğrultusunda tekrar edilmesi (döngü).", category: "Algoritma" },
    { term: "JWT (JSON Web Token)", definition: "İki taraf arasında güvenli şekilde bilgi transferi sağlayan, dijital olarak imzalanmış JSON formatıdır.", category: "Güvenlik" },
    { term: "Java", definition: "Yüksek performanslı, sınıf tabanlı ve nesne yönelimli, 'bir kez yaz her yerde çalıştır' felsefesine sahip dildir.", category: "Dil" },
    { term: "Jenkins", definition: "Yazılım geliştirme süreçlerini otomatize etmek için kullanılan popüler bir açık kaynaklı otomasyon sunucusudur.", category: "DevOps" },
    { term: "Koa.js", definition: "Express.js'in yaratıcıları tarafından tasarlanmış, daha küçük ve etkileyici bir Node.js frameworküdür.", category: "Backend" },
    { term: "Kotlin", definition: "JetBrains tarafından geliştirilen, modern ve güvenli bir Android uygulama geliştirme dilidir.", category: "Dil" },
    { term: "Late Binding", definition: "Metod çağrılarının derleme aşamasında değil, program çalışırken çözümlenmesi işlemidir.", category: "OOP" },
    { term: "Legacy Code", definition: "Aktif olarak kullanılan ancak güncel standartlara uymayan, genellikle bakımı zor eski kod parçalarıdır.", category: "Temel" },
    { term: "Linked List", definition: "Elemanların birbirine işaretçiler (pointer) ile bağlı olduğu dinamik bir veri yapısıdır.", category: "Veri Yapıları" },
    { term: "Load Balancer", definition: "Gelen ağ trafiğini birden fazla sunucuya dengeli şekilde dağıtan cihaz veya yazılımdır.", category: "Mimar" },
    { term: "Localhost", definition: "Bilgisayarın kendi kendisini ifade eden standart ana makine adıdır (127.0.0.1).", category: "Ağ" },
    { term: "Log", definition: "Sistemde gerçekleşen olayların zaman sırasına göre kaydedildiği dosyalardır.", category: "Test" },
    { term: "Markdown", definition: "Metinleri formatlamak için kullanılan hafif ve popüler bir işaretleme dilidir.", category: "Araç" },
    { term: "Memoization", definition: "Pahalı fonksiyon çağrılarının sonuçlarını saklayıp tekrar kullanma (optimizasyon) tekniğidir.", category: "Algoritma" },
    { term: "Middleware", definition: "İstek (request) ve yanıt (response) arasında çalışan, veriyi işleyen veya doğrulayan ara yazılımlardır.", category: "Backend" },
    { term: "Mocking", definition: "Testlerde gerçek nesnelerin yerini alan, önceden tanımlanmış davranışlara sahip taklit nesnelerdir.", category: "Test" },
    { term: "MySQL", definition: "Dünyanın en popüler açık kaynaklı ilişkisel veritabanı yönetim sistemidir (RDBMS).", category: "Veri" },
    { term: "Namespacing", definition: "Değişkenlerin ve sınıfların çakışmasını önlemek için kullanılan gruplandırma mekanizmasıdır.", category: "Temel" },
    { term: "Next.js", definition: "React tabanlı, sunucu taraflı render (SSR) ve statik site oluşturma desteği sunan bir frameworktür.", category: "Frontend" },
    { term: "Node.js", definition: "JavaScript kodlarını tarayıcı dışında, sunucu tarafında çalıştırmayı sağlayan çalışma ortamıdır.", category: "Backend" },
    { term: "OAuth", definition: "Şifre paylaşmadan bir uygulamanın başka bir uygulama üzerindeki verilere erişmesine izin veren protokoldür.", category: "Güvenlik" },
    { term: "ORM (Object-Relational Mapping)", definition: "Veritabanı işlemlerini nesne yönelimli olarak kod üzerinden yapmayı sağlayan tekniktir.", category: "Veri" },
    { term: "Overloading", definition: "Aynı isimli fakat farklı parametrelere sahip birden fazla metod tanımlama yeteneğidir.", category: "OOP" },
    { term: "Overriding", definition: "Alt sınıfın, üst sınıftan gelen bir metodu kendi ihtiyacına göre yeniden tanımlamasıdır.", category: "OOP" },
    { term: "Packet Sniffing", definition: "Bir ağ üzerinden geçen veri paketlerinin izlenmesi ve analiz edilmesi işlemidir.", category: "Ağ" },
    { term: "Paradigms (Programlama Paradigmaları)", definition: "Yazılım geliştirirken izlenen temel yaklaşımlardır (örn: Fonksiyonel, OOP).", category: "Dil" },
    { term: "Persistence", definition: "Verilerin sistem kapandıktan sonra da kalıcı olarak saklanması durumudur.", category: "Veri" },
    { term: "Polymorphism (Çok Biçimlilik)", definition: "Farklı nesnelerin aynı metoda farklı şekillerde yanıt verebilme yeteneğidir.", category: "OOP" },
    { term: "Postman", definition: "API'leri test etmek, dokümante etmek ve yönetmek için kullanılan en yaygın araçtır.", category: "Araç" },
    { term: "Protocol", definition: "İki sistem arasındaki iletişimin nasıl gerçekleşeceğini belirleyen kurallar setidir.", category: "Ağ" },
    { term: "Recursion (Özyineleme)", definition: "Bir fonksiyonun kendi kendisini çağırarak karmaşık problemleri çözmesi yöntemidir.", category: "Algoritma" },
    { term: "Redux", definition: "JavaScript uygulamalarında merkezi durum yönetimi (state management) sağlayan bir kütüphanedir.", category: "Frontend" },
    { term: "Runtime", definition: "Bir programın çalışmaya başladığı andan kapandığı ana kadar geçen süredir.", category: "Temel" },
    { term: "Scalability (Ölçeklenebilirlik)", definition: "Bir sistemin artan yükü verimli şekilde kaldırabilme ve büyüme yeteneğidir.", category: "Mimar" },
    { term: "Scripting Language", definition: "Derlenmeye ihtiyaç duymadan yorumlayıcı tarafından çalıştırılan dillerdir (örn: JS, Python).", category: "Dil" },
    { term: "SDK (Software Development Kit)", definition: "Belirli bir platform veya sistem için uygulama geliştirmeyi sağlayan araç/kütüphane paketidir.", category: "Araç" },
    { term: "Serializing", definition: "Bir veri yapısının veya nesnenin depolanmak/taşınmak için bir formata (örn: JSON) dönüştürülmesidir.", category: "Veri" },
    { term: "Serverless", definition: "Geliştiricinin sunucu yönetimiyle ilgilenmediği, sadece fonksiyon bazlı sistem mimarisidir.", category: "Cloud" },
    { term: "Shadow DOM", definition: "Web bileşenlerini izole etmek ve genel sayfa stillerinden etkilenmemesini sağlamak için kullanılan tekniktir.", category: "Frontend" },
    { term: "Singleton Pattern", definition: "Bir sınıftan çalışma süresi boyunca sadece bir tane nesne üretilmesini garanti eden desendir.", category: "Tasarım" },
    { term: "Socket.io", definition: "Web tarayıcıları ve sunucular arasında düşük gecikmeli, çift yönlü iletişim sağlayan kütüphanedir.", category: "JS" },
    { term: "Source Map", definition: "Minimize edilmiş kodun orijinal haline geri dönüştürülmesini ve hata ayıklamayı sağlayan haritadır.", category: "Araç" },
    { term: "SQL Injection", definition: "Kullanıcı girdisi üzerinden veritabanına zararlı SQL komutları gönderilmesine yol açan güvenlik açığıdır.", category: "Güvenlik" },
    { term: "Stack", definition: "Son giren ilk çıkar (LIFO) mantığıyla çalışan temel bir veri yapısıdır.", category: "Veri Yapıları" },
    { term: "Static Typing", definition: "Değişken türlerinin derleme aşamasında belirlendiği ve değiştirilemediği tipleme sistemidir.", category: "Dil" },
    { term: "Subnet Mask", definition: "Bir IP adresinin hangi kısmının ağa, hangi kısmının cihaza ait olduğunu belirleyen maskedir.", category: "Ağ" },
    { term: "Syntax (Sözdizimi)", definition: "Bir programlama dilinin karakterlerinin ve kelimelerinin doğru birleşim kurallarıdır.", category: "Dil" },
    { term: "Tailwind CSS", definition: "Hızlıca modern arayüzler tasarlamak için kullanılan düşük seviyeli, yardımcı sınıflar tabanlı bir CSS kütüphanedir.", category: "Frontend" },
    { term: "Throttling", definition: "Bir fonksiyonun belirli bir süre içinde en fazla kaç kez çalışabileceğini kısıtlama tekniğidir.", category: "JS" },
    { term: "Thread (İş Parçacığı)", definition: "Bir işlemin (process) içinde eş zamanlı olarak yürütülebilen en küçük birimdir.", category: "Temel" },
    { term: "Transaction", definition: "Veritabanında bir bütün olarak değerlendirilen ve ya tamamen başarılı olan ya da tamamen iptal edilen işlemlerdir.", category: "Veri" },
    { term: "Unit of Work", definition: "Birden fazla veritabanı işlemini tek bir işlem gibi tek seferde kaydetmeyi sağlayan tasarım desenidir.", category: "Tasarım" },
    { term: "V8 Engine", definition: "Google tarafından geliştirilen ve Chrome/Node.js tarafından kullanılan yüksek performanslı JavaScript motorudur.", category: "JS" },
    { term: "Virtual DOM", definition: "React gibi kütüphanelerin sayfa güncellemelerini hızlandırmak için hafızada tuttuğu döküman kopyasıdır.", category: "Frontend" },
    { term: "Vulnerability", definition: "Sistemin güvenliğini tehlikeye atabilecek her türlü zayıflık veya eksikliktir.", category: "Güvenlik" },
    { term: "Waterfall Model", definition: "Yazılım geliştirmenin her aşamasının bir sırayla ve bir öncekini bitirerek ilerlediği geleneksel modeldir.", category: "SDLC" },
    { term: "Webpack", definition: "Modern JavaScript uygulamaları için modülleri ve bağımlılıkları tek bir dosyada toplayan paketleyicidir.", category: "Araç" },
    { term: "Webhooks", definition: "Bir olay gerçekleştiğinde başka bir uygulamaya HTTP POST isteği gönderen otomatik bildirim sistemidir.", category: "Web" },
    { term: "Adware", definition: "Kullanıcıya istenmeyen reklamlar gösteren ve genellikle gizlice yüklenen yazılımlardır.", category: "Güvenlik" },
    { term: "Algorithm Complexity", definition: "Bir algoritmanın çalışması için gereken zaman ve alan kaynaklarının ölçüsüdür.", category: "Algoritma" },
    { term: "Alpha Testing", definition: "Yazılımın geliştirme süreci bitmeden, kurum içinde yapılan ilk kullanıcı testidir.", category: "Test" },
    { term: "Amazon S3", definition: "İnternet üzerinden veri depolamak için kullanılan ölçeklenebilir nesne depolama servisidir.", category: "Cloud" },
    { term: "Antipattern", definition: "Sık karşılaşılan bir probleme getirilen, ancak uzun vadede zararlı sonuçlar doğuran hatalı çözümlerdir.", category: "Tasarım" },
    { term: "Application Server", definition: "Uygulama mantığını çalıştıran ve web sunucusu ile veritabanı arasında köprü kuran sunucudur.", category: "Backend" },
    { term: "Architecture", definition: "Bir sistemin temel bileşenlerini, bunların birbirleriyle ilişkilerini ve yönetim prensiplerini belirleyen yapıdır.", category: "Mimar" },
    { term: "Artifact", definition: "Yazılım geliştirme sürecinde ortaya çıkan döküman, diyagram veya paketlenmiş kod dosyasıdır.", category: "Temel" },
    { term: "Assembly Language", definition: "Makine koduna çok yakın olan ve işlemci mimarisine doğrudan hitap eden düşük seviyeli dildir.", category: "Dil" },
    { term: "Authentication (Kimlik Doğrulama)", definition: "Bir kullanıcının gerçekten iddia ettiği kişi olduğunun kanıtlanması sürecidir.", category: "Güvenlik" },
    { term: "Authorization (Yetkilendirme)", definition: "Kimliği doğrulanmış bir kullanıcının hangi kaynaklara erişebileceğinin belirlenmesidir.", category: "Güvenlik" },
    { term: "Auto-Scaling", definition: "Sistem kaynaklarının trafik yoğunluğuna göre otomatik olarak artırılması veya azaltılmasıdır.", category: "Cloud" },
    { term: "Backlog", definition: "Yazılım projesinde tamamlanması gereken işlerin öncelik sırasına göre tutulduğu listedir.", category: "SDLC" },
    { term: "Backtesting", definition: "Bir strateji veya modelin geçmiş veriler üzerinde test edilerek performansının ölçülmesidir.", category: "Veri" },
    { term: "Bandwidth", definition: "Bir ağ bağlantısının birim zamanda taşıyabileceği maksimum veri miktarıdır.", category: "Ağ" },
    { term: "Bash", definition: "Unix tabanlı işletim sistemlerinde kullanılan popüler bir komut satırı yorumlayıcısıdır.", category: "OS" },
    { term: "Batch Processing", definition: "Verilerin biriktirilerek belirli zaman aralıklarıyla toplu halde işlenmesi yöntemidir.", category: "Veri" },
    { term: "Beta Testing", definition: "Yazılımın piyasaya sürülmeden önce sınırlı bir gerçek kullanıcı grubu tarafından test edilmesidir.", category: "Test" },
    { term: "Bias (Yapay Zeka)", definition: "Eğitim verilerindeki dengesizlikler nedeniyle algoritmanın belirli sonuçlara haksız şekilde yönelmesidir.", category: "AI" },
    { term: "Binding", definition: "Bir değişken isminin veya metodun bir adres ya da değer ile ilişkilendirilmesi sürecidir.", category: "Dil" },
    { term: "Bitrate", definition: "Dijital bir medyada saniyede aktarılan bit sayısıdır; kaliteyi doğrudan etkiler.", category: "Web" },
    { term: "Boundary Value Analysis", definition: "Girdi aralıklarının uç noktalarına odaklanarak yapılan bir yazılım test tekniğidir.", category: "Test" },
    { term: "Branding", definition: "Bir ürünün veya yazılımın kullanıcı nezdindeki görsel ve duygusal kimlik çalışmasıdır.", category: "Tasarım" },
    { term: "Bridge Pattern", definition: "Soyutlama ile uygulamayı birbirinden ayırarak bağımsız şekilde geliştirilmelerini sağlayan desendir.", category: "Tasarım" },
    { term: "Cache Invalidation", definition: "Önbellekteki verilerin güncelliğini yitirdiğinde temizlenmesi veya güncellenmesi sürecidir.", category: "Backend" },
    { term: "Canvas", definition: "HTML5 ile gelen, JavaScript kullanarak ekranda çizim ve animasyon yapmaya olanak tanıyan alandır.", category: "Frontend" },
    { term: "Checkpoint", definition: "Uzun süren bir işlemin kaydedilen ara durumudur; hata durumunda buradan devam edilebilir.", category: "Temel" },
    { term: "Classes (Sınıflar)", definition: "Nesne yönelimli programlamada nesnelerin özelliklerini ve davranışlarını tanımlayan şablonlardır.", category: "OOP" },
    { term: "Clean Code", definition: "Okunması, anlaşılması ve bakımı kolay olan, standartlara uygun yazılmış kod bütünüdür.", category: "Temel" },
    { term: "Cluster", definition: "Tek bir sistem gibi çalışan, birbirine bağlı bilgisayarlar veya sunucular grubudur.", category: "DevOps" },
    { term: "Cold Start", definition: "Serverless sistemlerde, uzun süre kullanılmayan bir fonksiyonun ilk çağrıda geç yanıt vermesi durumudur.", category: "Cloud" },
    { term: "Compiler (Derleyici)", definition: "Yüksek seviyeli kodları bilgisayarın anlayacağı makine diline çeviren yazılımdır.", category: "Temel" },
    { term: "Containerization", definition: "Uygulamaların tüm bağımlılıklarıyla beraber taşınabilir ve izole paketler haline getirilmesidir.", category: "DevOps" },
    { term: "Context", definition: "Bir işlemin veya kod bloğunun yürütüldüğü çevresel bilgileri ve durumu ifade eder.", category: "Temel" },
    { term: "Core Dump", definition: "Bir program çöktüğünde o anki bellek durumunun hata analizi için dosyaya kaydedilmesidir.", category: "Temel" },
    { term: "Crawl", definition: "Arama motoru botlarının web sayfalarını otomatik olarak ziyaret edip indekslemesi işlemidir.", category: "Web" },
    { term: "Cross-Platform", definition: "Bir yazılımın birden fazla farklı işletim sisteminde (Windows, Android, iOS vb.) çalışabilmesidir.", category: "Temel" },
    { term: "Cyber Attack", definition: "Dijital sistemleri bozmak, veri çalmak veya erişimi engellemek amacıyla yapılan kasıtlı girişimdir.", category: "Güvenlik" },
    { term: "Daemon", definition: "Arka planda sürekli çalışan ve kullanıcıyla doğrudan etkileşime girmeyen sistem servisleridir.", category: "OS" },
    { term: "Dashboard", definition: "Verilerin ve istatistiklerin görselleştirilerek tek bir ekranda sunulduğu yönetim panelidir.", category: "Tasarım" },
    { term: "Data Lake", definition: "Ham verilerin yapılandırılmış veya yapılandırılmamış şekilde orijinal formatında saklandığı geniş depodur.", category: "Veri" },
    { term: "Data Warehouse", definition: "Analiz ve raporlama için farklı kaynaklardan toplanmış, yapılandırılmış veri deposudur.", category: "Veri" },
    { term: "Debugger", definition: "Kod içerisindeki hataları adım adım izleyerek bulmaya ve düzeltmeye yarayan araçtır.", category: "Araç" },
    { term: "Deep Learning", definition: "Çok katmanlı yapay sinir ağlarını kullanarak karmaşık verilerden öğrenme sağlayan yapay zeka dalıdır.", category: "AI" },
    { term: "Default Parameter", definition: "Bir fonksiyon çağrılırken argüman gönderilmediğinde kullanılan varsayılan değerdir.", category: "Dil" },
    { term: "Density", definition: "Ekran çözünürlüğünde inç başına düşen piksel miktarını (DPI/PPI) ifade eder.", category: "Mobil" },
    { term: "Deprecation", definition: "Bir yazılım özelliğinin artık eskidiğini ve gelecekte kaldırılacağını belirten uyarı durumudur.", category: "Temel" },
    { term: "Deserializing", definition: "JSON veya dosya formatındaki veriyi tekrar program içerisindeki nesne veya veri yapısına dönüştürmedir.", category: "Veri" },
    { term: "DevOps", definition: "Yazılım geliştirme (Dev) ve sistem operasyonları (Ops) arasındaki iş birliğini artıran kültür ve pratiklerdir.", category: "Kültür" },
    { term: "Digital Signature", definition: "Bir dökümanın veya mesajın orijinalliğini ve bütünlüğünü kanıtlayan matematiksel koddur.", category: "Güvenlik" },
    { term: "Distributed Systems", definition: "Birden fazla bağımsız bilgisayarın, kullanıcıya tek bir sistem gibi göründüğü ağ yapılarıdır.", category: "Mimar" },
    { term: "Documentation", definition: "Yazılımın nasıl çalıştığını, nasıl kurulacağını ve API kullanımını anlatan rehberlerdir.", category: "Temel" },
    { term: "DotNet (.NET)", definition: "Microsoft tarafından geliştirilen kapsamlı bir yazılım geliştirme platformu ve frameworküdür.", category: "Framework" },
    { term: "DRY (Don't Repeat Yourself)", definition: "Aynı kod veya mantığın birden fazla yerde tekrar edilmemesi gerektiğini savunan prensiptir.", category: "Prensip" },
    { term: "Dynamic Typing", definition: "Değişken türlerinin program çalışırken (runtime) belirlendiği tipleme sistemidir.", category: "Dil" },
    { term: "E-Commerce", definition: "Ürün ve hizmetlerin internet üzerinden alım satımının yapıldığı sistemlerin genel adıdır.", category: "İş" },
    { term: "Edge Computing", definition: "Veri işlemenin merkezi bulut yerine verinin üretildiği yere (cihazlara) yakın yapılmasıdır.", category: "Cloud" },
    { term: "End-to-End (E2E) Testing", definition: "Tüm sistemin, kullanıcı akışı perspektifinden başından sonuna kadar test edilmesidir.", category: "Test" },
    { term: "Entity", definition: "Veritabanında veya kodda, gerçek hayattaki bir nesneyi temsil eden bağımsız varlıktır.", category: "Veri" },
    { term: "Environment Variables", definition: "Uygulamanın çalıştığı ortama özgü ayarları (API anahtarları, DB şifreleri vb.) tutan değişkenlerdir.", category: "Temel" },
    { term: "Error Handling", definition: "Programda çalışma anında oluşabilecek hataların tahmin edilmesi ve yönetilmesi sürecidir.", category: "Temel" },
    { term: "Escaping", definition: "Özel karakterlerin (örn: HTML etiketleri) yanlış yorumlanmaması için özel formata dönüştürülmesidir.", category: "Temel" },
    { term: "Event Loop", definition: "JavaScript gibi dillerde asenkron işlemleri yöneten, işlemleri sıraya koyan ve yürüten mekanizmadır.", category: "JS" },
    { term: "Event-Driven Architecture", definition: "Sistemin olaylar (tıklama, mesaj, hata vb.) üzerinden tetiklendiği ve haberleştiği mimaridir.", category: "Mimar" },
    { term: "Exception", definition: "Programın normal akışını bozan, çalışma zamanında ortaya çıkan beklenmedik olaylardır.", category: "Temel" },
    { term: "Experimental Feature", definition: "Henüz tam stabil olmayan, test amaçlı sunulan ileri seviye yazılım özellikleridir.", category: "Temel" },
    { term: "Exploit", definition: "Bir yazılım veya sistemdeki güvenlik açığını kullanarak sisteme sızmaya yarayan yöntem veya araçtır.", category: "Güvenlik" },
    { term: "Extensibility", definition: "Bir yazılımın mevcut yapısını bozmadan yeni özellikler eklenebilme kabiliyetidir.", category: "Mimar" },
    { term: "Feature Toggle", definition: "Bir özelliğin kodu silmeden canlı ortamda aktif veya deaktif edilmesini sağlayan tekniktir.", category: "DevOps" },
    { term: "Field", definition: "Bir sınıf içerisindeki veriyi saklayan en küçük birim, değişken.", category: "OOP" },
    { term: "File Descriptor", definition: "İşletim sisteminde bir dosyaya veya giriş/çıkış kanalına erişim sağlayan soyut anahtardır.", category: "OS" },
    { term: "Filter", definition: "Bir veri kümesi içerisinden belirli kriterlere uyan elemanları seçme işlemidir.", category: "Temel" },
    { term: "Firewall (Güvenlik Duvarı)", definition: "Gelen ve giden ağ trafiğini belirli kurallara göre izleyen ve filtreleyen güvenlik sistemidir.", category: "Güvenlik" },
    { term: "Flat File", definition: "Verilerin herhangi bir yapı veya ilişki olmadan düz metin halinde saklandığı dosyalardır.", category: "Veri" },
    { term: "Function", definition: "Belirli bir işlemi gerçekleştiren ve tekrar tekrar çağrılabilen isimlendirilmiş kod bloğudur.", category: "Temel" },
    { term: "Functional Programming", definition: "Programlamayı matematiksel fonksiyonlar ve değişmez veriler üzerine kurgulayan yaklaşımdır.", category: "Dil" },
    { term: "Full-Text Search", definition: "Bir metin dökümanı içerisindeki her kelimeye göre arama yapabilme yeteneğidir.", category: "Veri" },
    { term: "Game Engine", definition: "Oyun geliştirmek için gerekli temel fizik, render ve ses sistemlerini sunan yazılım iskeletidir.", category: "Oyun" },
    { term: "Gateway", definition: "Farklı ağ protokolleri kullanan sistemler arasında köprü kurarak veri geçişini sağlayan birimdir.", category: "Ağ" },
    { term: "Generic", definition: "Türden bağımsız olarak yazılan ve farklı veri türleriyle çalışabilen kod yapılarıdır (örn: List<T>).", category: "Dil" },
    { term: "Getter / Setter", definition: "Sınıf içindeki özel verilere güvenli şekilde erişmek ve güncellemek için kullanılan metodlardır.", category: "OOP" },
    { term: "Gherkin", definition: "Yazılım senaryolarını doğal dilde (Given, When, Then) yazmaya yarayan standart dildir.", category: "Test" },
    { term: "Global Variable", definition: "Programın her yerinden erişilebilen ve değiştirilebilen değişken türüdür.", category: "Temel" },
    { term: "GPU (Graphics Processing Unit)", definition: "Görsel hesaplamalar ve paralel işlem gerektiren görevler için özelleşmiş işlemcidir.", category: "Donanım" },
    { term: "Gray Box Testing", definition: "Yazılımın hem iç yapısını kısmen bilerek hem de dış davranışını izleyerek yapılan testtir.", category: "Test" },
    { term: "Grid System", definition: "Web tasarımında içerikleri hizalamak için kullanılan satır ve sütun temelli mizanpaj yapısıdır.", category: "Frontend" },
    { term: "Handle", definition: "İşletim sistemi tarafından yönetilen bir kaynağa erişmek için program tarafında kullanılan referanstır.", category: "OS" },
    { term: "Hard Coding", definition: "Parametrelerin veya ayarların dışarıdan alınmak yerine doğrudan kodun içine sabitlenmesi işlemidir.", category: "Temel" },
    { term: "Hardware", definition: "Bilgisayarı oluşturan fiziksel bileşenlerin (işlemci, disk, ram vb.) genel adıdır.", category: "Temel" },
    { term: "Headless CMS", definition: "Arayüzü olmayan, sadece API (genellikle REST/GraphQL) üzerinden içerik sunan içerik yönetim sistemidir.", category: "Web" },
    { term: "Heap", definition: "Programın çalışma süresince dinamik olarak ayrılan bellek bölgesidir.", category: "Temel" },
    { term: "Heuristics", definition: "Kesin garanti vermese de çoğu zaman pratik ve hızlı sonuç üreten problem çözme yöntemleridir.", category: "Algoritma" },
    { term: "Higher-Order Function", definition: "Argüman olarak fonksiyon alan veya sonuç olarak fonksiyon döndüren fonksiyonlardır.", category: "Dil" },
    { term: "Hotfix", definition: "Üretim ortamındaki kritik bir hatayı acilen düzeltmek için yayınlanan küçük güncellemedir.", category: "SDLC" },
    { term: "Hybrid App", definition: "Hem web teknolojileriyle yazılmış hem de yerel (native) özelliklere erişebilen mobil uygulamalardır.", category: "Mobil" },
    { term: "Hyperlink", definition: "Bir web sayfasından başka bir dökümana veya konuma gitmeyi sağlayan köprüdür.", category: "Web" },
    { term: "Icon", definition: "Bir işlevi veya nesneyi temsil eden küçük, sembolik görsel öğedir.", category: "Tasarım" },
    { term: "Iframe", definition: "Bir HTML dökümanı içerisine başka bir web sayfasını gömmeye yarayan etikettir.", category: "Frontend" },
    { term: "Image Processing", definition: "Dijital görüntüleri algoritmalar kullanarak analiz etme ve geliştirme sürecidir.", category: "AI" },
    { term: "Inbound Link", definition: "Başka bir web sitesinden sizin sitenize verilen bağlantıdır; SEO için önemlidir.", category: "Web" },
    { term: "Indexing", definition: "Veritabanında verilere hızlı erişim sağlamak için oluşturulan veri yapısıdır.", category: "Veri" },
    { term: "Information Architecture", definition: "Bir web sitesi veya uygulamanın içeriğinin mantıksal düzenleme ve isimlendirilmesi sürecidir.", category: "Tasarım" },
    { term: "Input", definition: "Kullanıcıdan veya başka bir sistemden alınan her türlü veri girişidir.", category: "Temel" },
    { term: "Instance", definition: "Bir sınıftan (class) türetilmiş olan somut nesne örneğidir.", category: "OOP" },
    { term: "Integration Testing", definition: "Farklı yazılım modüllerinin bir arada çalışabilirliğinin kontrol edildiği test aşamasıdır.", category: "Test" },
    { term: "Interface Segregation", definition: "Bir arayüzün, istemcilerin ihtiyaç duymadığı metodları içermemesi gerektiğini savunan SOLID prensibidir.", category: "Prensip" },
    { term: "Interpreter (Yorumlayıcı)", definition: "Kod satırlarını derlemeden, çalışma anında sırayla yürüten yazılımdır.", category: "Temel" },
    { term: "Intranet", definition: "Sadece bir kurum veya kuruluş içerisindeki yetkili kişilerce erişilebilen özel ağdır.", category: "Ağ" },
    { term: "Invariant", definition: "Programın belirli bir kısmında her zaman doğru olması beklenen mantıksal koşuldur.", category: "Temel" },
    { term: "IoT (Internet of Things)", definition: "Nesnelerin internet üzerinden birbirleriyle veri alışverişi yapabildiği cihazlar ekosistemidir.", category: "Teknoloji" },
    { term: "Iteration Planning", definition: "Belirli bir zaman diliminde (sprint) hangi işlerin yapılacağının kararlaştırıldığı toplantıdır.", category: "SDLC" },
    { term: "JIT Compiler (Just-In-Time)", definition: "Kodun çalışma anında derlenerek performans artışı sağlayan derleme tekniğidir.", category: "Temel" },
    { term: "Kanban", definition: "İş akışını görselleştirerek verimliliği artırmaya odaklanan bir proje yönetim metodolojisidir.", category: "SDLC" },
    { term: "Kernel", definition: "İşletim sisteminin donanım ve yazılım arasındaki iletişimi sağlayan en temel çekirdek kısmıdır.", category: "OS" },
    { term: "Keyword", definition: "Programlama dillerinde özel bir anlamı olan ve değişken adı olarak kullanılamayan kelimelerdir.", category: "Dil" },
    { term: "Lambda Expression", definition: "İsimsiz, tek satırlık pratik fonksiyon tanımlama yöntemidir.", category: "Dil" },
    { term: "Latency", definition: "Verinin bir noktadan diğerine ulaşması sırasında oluşan gecikme süresidir.", category: "Ağ" },
    { term: "Lazy Loading", definition: "Kaynakların (resim, video, modül vb.) sadece ihtiyaç duyulduğu anda yüklenmesi tekniğidir.", category: "Web" },
    { term: "Least Privilege", definition: "Bir kullanıcıya veya sisteme sadece yapacağı iş için gereken minimum yetkinin verilmesi kuralıdır.", category: "Güvenlik" },
    { term: "Library", definition: "Belirli işlemleri gerçekleştirmek için hazır fonksiyonlar sunan kod arşividir.", category: "Temel" },
    { term: "Lifo (Last In First Out)", definition: "Son giren elemanın ilk çıktığı veri yapısı mantığıdır (örn: Stack).", category: "Veri Yapıları" },
    { term: "Linting", definition: "Kodun hatalara, stil yanlışlarına ve şüpheli yapılara karşı otomatik analiz edilmesidir.", category: "Araç" },
    { term: "LSP (Liskov Substitution)", definition: "Alt sınıfların, üst sınıfların yerine hiçbir sorun çıkmadan kullanılabilmesi gerektiğini savunan SOLID prensibidir.", category: "Prensip" },
    { term: "Maintainability", definition: "Yazılımın zamanla kolayca güncellenebilme, hata ayıklanabilme ve geliştirilebilme yeteneğidir.", category: "Mimar" },
    { term: "Malware", definition: "Sistemlere zarar vermek amacıyla tasarlanmış her türlü kötü amaçlı yazılımın genel adıdır.", category: "Güvenlik" },
    { term: "Managed Code", definition: "Çalışma anı (runtime) tarafından yönetilen ve bellek yönetimi gibi görevlerin otomatik yapıldığı koddur.", category: "Temel" },
    { term: "Manifest File", definition: "Proje veya paket hakkında meta bilgileri ve yapılandırma ayarlarını içeren dosyadır.", category: "Temel" },
    { term: "MapReduce", definition: "Büyük veri setlerini paralel olarak işlemek ve özetlemek için kullanılan programlama modelidir.", category: "Veri" },
    { term: "Metadata", definition: "Verinin kendisi yerine, o veri hakkında bilgi veren (yazar, tarih, boyut vb.) veridir.", category: "Veri" },
    { term: "Microkernel", definition: "Sadece en temel görevleri yerine getiren ve diğer servisleri kullanıcı alanında çalıştıran işletim sistemi çekirdeğidir.", category: "OS" },
    { term: "Migration", definition: "Verilerin veya uygulamanın bir sistemden/platformdan başka birine taşınması sürecidir.", category: "Temel" },
    { term: "Minification", definition: "Kodun işlevini bozmadan dosya boyutunu küçültmek için boşlukların ve gereksiz karakterlerin silinmesi işlemidir.", category: "Frontend" },
    { term: "Monolith", definition: "Tüm fonksiyonların tek bir büyük kod tabanı ve birim içerisinde toplandığı geleneksel yazılım mimarisidir.", category: "Mimar" },
    { term: "Multithreading", definition: "Bir programın aynı anda birden fazla iş parçacığı (thread) yürüterek performans artırmasıdır.", category: "Temel" },
    { term: "Namespace", definition: "Kod içerisinde isim çakışmalarını önlemek için oluşturulan mantıksal gruplandırma alanıdır.", category: "Dil" },
    { term: "Native App", definition: "Belirli bir platform (Android veya iOS) için o platformun ana diliyle yazılmış yüksek performanslı uygulamadır.", category: "Mobil" },
    { term: "Negative Testing", definition: "Yazılımın geçersiz veya beklenmedik girdiler karşısındaki davranışını ölçmek için yapılan testtir.", category: "Test" },
    { term: "Neural Networks", definition: "İnsan beyninin çalışma yapısını taklit eden ve yapay zekada kullanılan karmaşık matematiksel modellerdir.", category: "AI" },
    { term: "Nginx", definition: "Yüksek performanslı, hafif ve popüler bir web sunucusu ve ters vekil (reverse proxy) yazılımıdır.", category: "DevOps" },
    { term: "Node", definition: "Bir ağ üzerindeki her bir cihazı veya bir veri yapısındaki (örn: ağaç) her bir düğümü ifade eder.", category: "Temel" },
    { term: "Normalization", definition: "Veritabanında veri tekrarını önlemek ve veri bütünlüğünü sağlamak için uygulanan tasarım sürecidir.", category: "Veri" },
    { term: "No-Code", definition: "Hiç kod yazmadan, görsel sürükle-bırak araçlarıyla yazılım geliştirme yaklaşımıdır.", category: "Teknoloji" },
    { term: "Nullable", definition: "Bir değişkenin geçerli bir değer dışında 'null' (boş) değerini de alabileceğini ifade eder.", category: "Dil" },
    { term: "Object", definition: "Sınıflardan türetilen, durumu (özellik) ve davranışı (metod) olan yazılım birimidir.", category: "OOP" },
    { term: "On-Premise", definition: "Yazılımın bulut yerine şirketin kendi fiziksel sunucularında kurulması ve çalıştırılmasıdır.", category: "İş" },
    { term: "Open/Closed Principle", definition: "Yazılım birimlerinin geliştirmeye açık ancak değişime kapalı olması gerektiğini savunan SOLID prensibidir.", category: "Prensip" },
    { term: "Overhead", definition: "Bir işlemin ana görevi dışında tükettiği ek kaynak (zaman, bellek vb.) miktarıdır.", category: "Temel" },
    { term: "Package Manager", definition: "Kütüphane ve bağımlılıkların otomatik olarak kurulmasını ve güncellenmesini sağlayan araçtır (örn: npm, pip).", category: "Araç" },
    { term: "Pair Programming", definition: "İki yazılımcının aynı bilgisayar başında, birinin kod yazıp diğerinin incelediği ortak çalışma yöntemidir.", category: "Kültür" },
    { term: "Parallel Computing", definition: "Birden fazla işlemin aynı anda farklı işlemcilerde yürütülerek hız kazanılmasıdır.", category: "Temel" },
    { term: "Parameter", definition: "Bir fonksiyona dışarıdan gönderilen ve fonksiyon içinde kullanılan girdi bilgisidir.", category: "Temel" },
    { term: "Parent Class", definition: "Kalıtım yoluyla özelliklerini alt sınıflara aktaran temel sınıf (Superclass).", category: "OOP" },
    { term: "Pattern Matching", definition: "Belirli bir veri yapısı veya metin içerisinde aranan kalıbın bulunması işlemidir.", category: "Algoritma" },
    { term: "Payload", definition: "Bir veri paketinin veya API isteğinin asıl taşımak istediği faydalı veri içeriğidir.", category: "Web" },
    { term: "Penetration Testing", definition: "Sistemin güvenlik açıklarını bulmak için yapılan etik hackerlık ve sızma testleri sürecidir.", category: "Güvenlik" },
    { term: "Performance Tuning", definition: "Bir yazılımın hızını artırmak ve kaynak tüketimini optimize etmek için yapılan iyileştirmelerdir.", category: "Temel" },
    { term: "Persistence Layer", definition: "Uygulamanın veritabanı ile haberleştiği ve verileri kalıcı hale getirdiği katmandır.", category: "Mimar" },
    { term: "Permissions", definition: "Kullanıcıların sistem üzerindeki dosyaları okuma, yazma veya yürütme yetkileridir.", category: "Güvenlik" },
    { term: "Phishing", definition: "Kullanıcıları sahte web siteleriyle kandırarak şifre veya kredi kartı bilgilerini çalma yöntemidir.", category: "Güvenlik" },
    { term: "Pipe", definition: "Bir programın çıktısını, ara aşama olmadan doğrudan başka bir programın girdisi olarak kullanma tekniğidir.", category: "OS" },
    { term: "Platform", definition: "Bir yazılımın çalışması için gereken temel donanım ve yazılım ortamıdır.", category: "Temel" },
    { term: "Plugin", definition: "Mevcut bir yazılıma ek özellik kazandıran ve kolayca eklenip çıkarılabilen eklenti paketidir.", category: "Temel" },
    { term: "Pointer", definition: "Doğrudan bir veri yerine, o verinin bellekteki adresini tutan özel bir değişken türüdür.", category: "Dil" },
    { term: "PostgreSQL", definition: "Gelişmiş özelliklere sahip, açık kaynaklı ve güçlü bir ilişkisel veritabanı yönetim sistemidir.", category: "Veri" },
    { term: "Primitive Types", definition: "Bir programlama dilindeki en basit veri türleridir (örn: integer, boolean, char).", category: "Dil" },
    { term: "Production Environment", definition: "Yazılımın son kullanıcılara sunulduğu ve canlı olarak çalıştığı en son ortamdır.", category: "DevOps" },
    { term: "Proxy Server", definition: "İstemci ile hedef sunucu arasında aracı olarak çalışan ve istekleri ileten sunucudur.", category: "Ağ" },
    { term: "Pull Request", definition: "Yapılan kod değişikliklerinin ana projeye dahil edilmesi için gönderilen inceleme ve onay isteğidir.", category: "Araç" },
    { term: "QA (Quality Assurance)", definition: "Yazılımın belirlenen kalite standartlarına uygunluğunu denetleyen kalite güvence sürecidir.", category: "Test" },
    { term: "Queue", definition: "İlk giren ilk çıkar (FIFO) mantığıyla çalışan, kuyruk yapısındaki veri yapısıdır.", category: "Veri Yapıları" },
    { term: "Radix Sort", definition: "Sayıları basamak değerlerine göre sıralayan, karşılaştırma yapmayan bir sıralama algoritmasıdır.", category: "Algoritma" },
    { term: "RAM (Random Access Memory)", definition: "Bilgisayarın çalışan programları ve verileri geçici olarak sakladığı hızlı erişim belleğidir.", category: "Donanım" },
    { term: "Refining", definition: "Yazılım gereksinimlerinin veya kodun daha net ve kaliteli hale getirilmesi sürecidir.", category: "SDLC" },
    { term: "Regex (Regular Expressions)", definition: "Metinler içerisinde karmaşık desenleri aramak ve yakalamak için kullanılan standart dizilim kurallarıdır.", category: "Araç" },
    { term: "Registry", definition: "Sistem ayarlarının ve konfigürasyon bilgilerinin saklandığı merkezi veritabanı veya kayıt dizinidir.", category: "OS" },
    { term: "Regression Testing", definition: "Yapılan değişikliklerin mevcut çalışan özellikleri bozup bozmadığını kontrol etmek için yapılan testtir.", category: "Test" },
    { term: "Repository", definition: "Proje dosyalarının ve versiyon geçmişinin saklandığı dijital depodur.", category: "Araç" },
    { term: "RESTful", definition: "REST mimari prensiplerine uygun olarak tasarlanmış olan web servislerine verilen addır.", category: "Backend" },
    { term: "Return Value", definition: "Bir fonksiyonun çalışmasını bitirdiğinde çağıran birime gönderdiği sonuç değeridir.", category: "Dil" },
    { term: "Rollback", definition: "Bir güncellemenin veya işlemin başarısız olması durumunda sistemi bir önceki kararlı duruma geri döndürme işlemidir.", category: "DevOps" },
    { term: "Root", definition: "Bir sistemdeki veya ağaç yapısındaki en yetkili kullanıcı veya başlangıç noktasıdır.", category: "OS" },
    { term: "Router", definition: "Ağ trafiğini en uygun yoldan hedef adreslere yönlendiren cihaz veya yazılım birimidir.", category: "Ağ" },
    { term: "Runtime Error", definition: "Program çalışırken, mantıksal bir sorun veya kaynak yetersizliği nedeniyle oluşan hatadır.", category: "Temel" },
    { term: "Safety Critical", definition: "Hata yapması durumunda insan hayatına veya büyük maddi kayba yol açabilecek kritik sistemlerdir.", category: "Mimar" },
    { term: "Sandbox", definition: "Yazılımların sistemin geri kalanından izole edilerek güvenli bir ortamda test edilmesi veya çalıştırılmasıdır.", category: "Güvenlik" },
    { term: "Scope", definition: "Bir değişkenin veya fonksiyonun programın hangi bölümlerinden erişilebilir olduğunu belirleyen kapsama alanıdır.", category: "Dil" },
    { term: "SDK", definition: "Yazılımcıların belirli bir platform için uygulama geliştirmesini sağlayan hazır araç ve kütüphane setidir.", category: "Araç" },
    { term: "Searching Algorithm", definition: "Veri seti içerisinde belirli bir elemanı bulmak için kullanılan mantıksal yöntemlerdir.", category: "Algoritma" },
    { term: "Server", definition: "İstemcilerden gelen isteklere yanıt veren ve kaynak/hizmet sunan güçlü bilgisayar sistemidir.", category: "Temel" },
    { term: "Service Worker", definition: "Tarayıcıda arka planda çalışan, çevrimdışı destek ve bildirim gibi özellikleri sağlayan scriptlerdir.", category: "Web" },
    { term: "Session", definition: "Kullanıcının bir uygulama ile girdiği etkileşimin, sunucu tarafında belirli bir süre için tutulan oturum bilgisidir.", category: "Web" },
    { term: "Side Effect", definition: "Bir fonksiyonun kendi iç görevi dışında programın durumunda (state) yaptığı değişikliklerdir.", category: "Dil" },
    { term: "Slave Node", definition: "Dağıtık sistemlerde bir ana düğüm (master) tarafından kontrol edilen ve görevleri yerine getiren birimdir.", category: "Mimar" },
    { term: "Solid Principles", definition: "Daha esnek, bakımı kolay ve ölçeklenebilir yazılımlar yazmak için takip edilen beş temel tasarım prensibidir.", category: "Prensip" },
    { term: "Source Code", definition: "Yazılımcı tarafından okunabilir formda yazılmış olan bir programın temel kod dökümanıdır.", category: "Temel" },
    { term: "Sprint", definition: "Scrum metodolojisinde, üzerinde çalışılan işlerin bitirildiği 1-4 hafta arası kısa çalışma dönemidir.", category: "SDLC" },
    { term: "SSH (Secure Shell)", definition: "Uzak sunuculara güvenli ve şifreli şekilde erişim sağlamayı amaçlayan ağ protokolüdür.", category: "Güvenlik" }
];
